// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  handler

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AuthHandler ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AuthHandler ) UnmarshalJSON([]byte) error { return nil }
func ( AuthHandler ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AuthHandler ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AuthHandler *AuthHandler

func ( RegisterRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RegisterRequest ) UnmarshalJSON([]byte) error { return nil }
func ( RegisterRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RegisterRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RegisterRequest *RegisterRequest
