// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handler

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler(in *jlexer.Lexer, out *WithdrawalResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "order":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Order = string(in.String())
			}
		case "sum":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sum = float64(in.Float64())
			}
		case "processed_at":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProcessedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler(out *jwriter.Writer, in WithdrawalResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.Order))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Sum))
	}
	{
		const prefix string = ",\"processed_at\":"
		out.RawString(prefix)
		out.String(string(in.ProcessedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawalResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawalResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawalResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawalResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler(l, v)
}
func easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler1(in *jlexer.Lexer, out *WithdrawalRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "order":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Order = string(in.String())
			}
		case "sum":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sum = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler1(out *jwriter.Writer, in WithdrawalRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.Order))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Sum))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WithdrawalRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WithdrawalRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WithdrawalRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WithdrawalRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler1(l, v)
}
func easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler2(in *jlexer.Lexer, out *BalanceHandler) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler2(out *jwriter.Writer, in BalanceHandler) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BalanceHandler) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BalanceHandler) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBed2650eEncodeGithubComKV2013GophermartLoyaltyInternalHandler2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BalanceHandler) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BalanceHandler) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBed2650eDecodeGithubComKV2013GophermartLoyaltyInternalHandler2(l, v)
}
